version: "3.3"
services:
  api:
    image: # edit this
    ports:
      - 3000:3000
    volumes:
      - ./src:/server
    environment:
      - PORT=3000
      - SWAGGER_HOSTS=http://localhost:3000,http://localhost/oauth2/
